export type {Entity} from '@rocicorp/zql/dist/entity.js';
export type {EntityQuery} from '@rocicorp/zql/dist/zql/query/entity-query.js';
export {
  IDBNotFoundError,
  TransactionClosedError,
  dropAllDatabases,
  dropDatabase,
  getDefaultPuller,
  makeIDBName,
} from 'replicache';
export type {
  // based on reflect-shared/out/mod.ts, but slimmed
  AsyncIterableIteratorToArray,
  ClientGroupID,
  ClientID,
  CreateKVStore,
  ExperimentalDiff,
  ExperimentalDiffOperation,
  ExperimentalDiffOperationAdd,
  ExperimentalDiffOperationChange,
  ExperimentalDiffOperationDel,
  ExperimentalIndexDiff,
  ExperimentalNoIndexDiff,
  ExperimentalWatchCallbackForOptions,
  ExperimentalWatchIndexCallback,
  ExperimentalWatchIndexOptions,
  ExperimentalWatchNoIndexCallback,
  ExperimentalWatchNoIndexOptions,
  ExperimentalWatchOptions,
  GetIndexScanIterator,
  GetScanIterator,
  HTTPRequestInfo,
  IndexDefinition,
  IndexDefinitions,
  IndexKey,
  IterableUnion,
  JSONObject,
  JSONValue,
  KVRead,
  KVStore,
  KVWrite,
  KeyTypeForScanOptions,
  MaybePromise,
  MutatorDefs,
  MutatorReturn,
  PatchOperation,
  ReadTransaction,
  ReadonlyJSONObject,
  ReadonlyJSONValue,
  ScanIndexOptions,
  ScanNoIndexOptions,
  ScanOptionIndexedStartKey,
  ScanOptions,
  ScanResult,
  SubscribeOptions,
  TransactionEnvironment,
  TransactionLocation,
  TransactionReason,
  UpdateNeededReason,
  VersionNotSupportedResponse,
  WriteTransaction,
} from 'replicache';
export type {ZeroOptions} from './client/options.js';
export {Zero, QueryDefs} from './client/zero.js';
