#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" == "main" ]]; then
  npm run publish-worker-prod
else
  npm run publish-worker-staging
fi

